// Generated by gencpp from file pingclient/PingPongResponse.msg
// DO NOT EDIT!


#ifndef PINGCLIENT_MESSAGE_PINGPONGRESPONSE_H
#define PINGCLIENT_MESSAGE_PINGPONGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pingclient
{
template <class ContainerAllocator>
struct PingPongResponse_
{
  typedef PingPongResponse_<ContainerAllocator> Type;

  PingPongResponse_()
    : receiving()  {
    }
  PingPongResponse_(const ContainerAllocator& _alloc)
    : receiving(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _receiving_type;
  _receiving_type receiving;




  typedef boost::shared_ptr< ::pingclient::PingPongResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pingclient::PingPongResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PingPongResponse_

typedef ::pingclient::PingPongResponse_<std::allocator<void> > PingPongResponse;

typedef boost::shared_ptr< ::pingclient::PingPongResponse > PingPongResponsePtr;
typedef boost::shared_ptr< ::pingclient::PingPongResponse const> PingPongResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pingclient::PingPongResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pingclient::PingPongResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pingclient

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pingclient::PingPongResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pingclient::PingPongResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pingclient::PingPongResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pingclient::PingPongResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pingclient::PingPongResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pingclient::PingPongResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pingclient::PingPongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "34b10a743589ef0c962bbd4132f67456";
  }

  static const char* value(const ::pingclient::PingPongResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x34b10a743589ef0cULL;
  static const uint64_t static_value2 = 0x962bbd4132f67456ULL;
};

template<class ContainerAllocator>
struct DataType< ::pingclient::PingPongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pingclient/PingPongResponse";
  }

  static const char* value(const ::pingclient::PingPongResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pingclient::PingPongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string receiving\n\
\n\
";
  }

  static const char* value(const ::pingclient::PingPongResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pingclient::PingPongResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.receiving);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PingPongResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pingclient::PingPongResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pingclient::PingPongResponse_<ContainerAllocator>& v)
  {
    s << indent << "receiving: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.receiving);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PINGCLIENT_MESSAGE_PINGPONGRESPONSE_H
