// Generated by gencpp from file turtlesim1/Kill.msg
// DO NOT EDIT!


#ifndef TURTLESIM1_MESSAGE_KILL_H
#define TURTLESIM1_MESSAGE_KILL_H

#include <ros/service_traits.h>


#include <turtlesim1/KillRequest.h>
#include <turtlesim1/KillResponse.h>


namespace turtlesim1
{

struct Kill
{

typedef KillRequest Request;
typedef KillResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Kill
} // namespace turtlesim1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim1::Kill > {
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::turtlesim1::Kill&) { return value(); }
};

template<>
struct DataType< ::turtlesim1::Kill > {
  static const char* value()
  {
    return "turtlesim1/Kill";
  }

  static const char* value(const ::turtlesim1::Kill&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim1::KillRequest> should match 
// service_traits::MD5Sum< ::turtlesim1::Kill > 
template<>
struct MD5Sum< ::turtlesim1::KillRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::Kill >::value();
  }
  static const char* value(const ::turtlesim1::KillRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::KillRequest> should match 
// service_traits::DataType< ::turtlesim1::Kill > 
template<>
struct DataType< ::turtlesim1::KillRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::Kill >::value();
  }
  static const char* value(const ::turtlesim1::KillRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim1::KillResponse> should match 
// service_traits::MD5Sum< ::turtlesim1::Kill > 
template<>
struct MD5Sum< ::turtlesim1::KillResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::Kill >::value();
  }
  static const char* value(const ::turtlesim1::KillResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::KillResponse> should match 
// service_traits::DataType< ::turtlesim1::Kill > 
template<>
struct DataType< ::turtlesim1::KillResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::Kill >::value();
  }
  static const char* value(const ::turtlesim1::KillResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM1_MESSAGE_KILL_H
