// Generated by gencpp from file turtlesim1/SetPen.msg
// DO NOT EDIT!


#ifndef TURTLESIM1_MESSAGE_SETPEN_H
#define TURTLESIM1_MESSAGE_SETPEN_H

#include <ros/service_traits.h>


#include <turtlesim1/SetPenRequest.h>
#include <turtlesim1/SetPenResponse.h>


namespace turtlesim1
{

struct SetPen
{

typedef SetPenRequest Request;
typedef SetPenResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPen
} // namespace turtlesim1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim1::SetPen > {
  static const char* value()
  {
    return "9f452acce566bf0c0954594f69a8e41b";
  }

  static const char* value(const ::turtlesim1::SetPen&) { return value(); }
};

template<>
struct DataType< ::turtlesim1::SetPen > {
  static const char* value()
  {
    return "turtlesim1/SetPen";
  }

  static const char* value(const ::turtlesim1::SetPen&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim1::SetPenRequest> should match 
// service_traits::MD5Sum< ::turtlesim1::SetPen > 
template<>
struct MD5Sum< ::turtlesim1::SetPenRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::SetPen >::value();
  }
  static const char* value(const ::turtlesim1::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::SetPenRequest> should match 
// service_traits::DataType< ::turtlesim1::SetPen > 
template<>
struct DataType< ::turtlesim1::SetPenRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::SetPen >::value();
  }
  static const char* value(const ::turtlesim1::SetPenRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim1::SetPenResponse> should match 
// service_traits::MD5Sum< ::turtlesim1::SetPen > 
template<>
struct MD5Sum< ::turtlesim1::SetPenResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::SetPen >::value();
  }
  static const char* value(const ::turtlesim1::SetPenResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::SetPenResponse> should match 
// service_traits::DataType< ::turtlesim1::SetPen > 
template<>
struct DataType< ::turtlesim1::SetPenResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::SetPen >::value();
  }
  static const char* value(const ::turtlesim1::SetPenResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM1_MESSAGE_SETPEN_H
