// Generated by gencpp from file turtlesim1/Spawn.msg
// DO NOT EDIT!


#ifndef TURTLESIM1_MESSAGE_SPAWN_H
#define TURTLESIM1_MESSAGE_SPAWN_H

#include <ros/service_traits.h>


#include <turtlesim1/SpawnRequest.h>
#include <turtlesim1/SpawnResponse.h>


namespace turtlesim1
{

struct Spawn
{

typedef SpawnRequest Request;
typedef SpawnResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Spawn
} // namespace turtlesim1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim1::Spawn > {
  static const char* value()
  {
    return "0b2d2e872a8e2887d5ed626f2bf2c561";
  }

  static const char* value(const ::turtlesim1::Spawn&) { return value(); }
};

template<>
struct DataType< ::turtlesim1::Spawn > {
  static const char* value()
  {
    return "turtlesim1/Spawn";
  }

  static const char* value(const ::turtlesim1::Spawn&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim1::SpawnRequest> should match 
// service_traits::MD5Sum< ::turtlesim1::Spawn > 
template<>
struct MD5Sum< ::turtlesim1::SpawnRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::Spawn >::value();
  }
  static const char* value(const ::turtlesim1::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::SpawnRequest> should match 
// service_traits::DataType< ::turtlesim1::Spawn > 
template<>
struct DataType< ::turtlesim1::SpawnRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::Spawn >::value();
  }
  static const char* value(const ::turtlesim1::SpawnRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim1::SpawnResponse> should match 
// service_traits::MD5Sum< ::turtlesim1::Spawn > 
template<>
struct MD5Sum< ::turtlesim1::SpawnResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::Spawn >::value();
  }
  static const char* value(const ::turtlesim1::SpawnResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::SpawnResponse> should match 
// service_traits::DataType< ::turtlesim1::Spawn > 
template<>
struct DataType< ::turtlesim1::SpawnResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::Spawn >::value();
  }
  static const char* value(const ::turtlesim1::SpawnResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM1_MESSAGE_SPAWN_H
