// Generated by gencpp from file turtlesim1/TeleportRelative.msg
// DO NOT EDIT!


#ifndef TURTLESIM1_MESSAGE_TELEPORTRELATIVE_H
#define TURTLESIM1_MESSAGE_TELEPORTRELATIVE_H

#include <ros/service_traits.h>


#include <turtlesim1/TeleportRelativeRequest.h>
#include <turtlesim1/TeleportRelativeResponse.h>


namespace turtlesim1
{

struct TeleportRelative
{

typedef TeleportRelativeRequest Request;
typedef TeleportRelativeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportRelative
} // namespace turtlesim1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim1::TeleportRelative > {
  static const char* value()
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const ::turtlesim1::TeleportRelative&) { return value(); }
};

template<>
struct DataType< ::turtlesim1::TeleportRelative > {
  static const char* value()
  {
    return "turtlesim1/TeleportRelative";
  }

  static const char* value(const ::turtlesim1::TeleportRelative&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim1::TeleportRelativeRequest> should match 
// service_traits::MD5Sum< ::turtlesim1::TeleportRelative > 
template<>
struct MD5Sum< ::turtlesim1::TeleportRelativeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::TeleportRelativeRequest> should match 
// service_traits::DataType< ::turtlesim1::TeleportRelative > 
template<>
struct DataType< ::turtlesim1::TeleportRelativeRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelativeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim1::TeleportRelativeResponse> should match 
// service_traits::MD5Sum< ::turtlesim1::TeleportRelative > 
template<>
struct MD5Sum< ::turtlesim1::TeleportRelativeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelativeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::TeleportRelativeResponse> should match 
// service_traits::DataType< ::turtlesim1::TeleportRelative > 
template<>
struct DataType< ::turtlesim1::TeleportRelativeResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::TeleportRelative >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelativeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM1_MESSAGE_TELEPORTRELATIVE_H
