// Generated by gencpp from file turtlesim1/TeleportAbsolute.msg
// DO NOT EDIT!


#ifndef TURTLESIM1_MESSAGE_TELEPORTABSOLUTE_H
#define TURTLESIM1_MESSAGE_TELEPORTABSOLUTE_H

#include <ros/service_traits.h>


#include <turtlesim1/TeleportAbsoluteRequest.h>
#include <turtlesim1/TeleportAbsoluteResponse.h>


namespace turtlesim1
{

struct TeleportAbsolute
{

typedef TeleportAbsoluteRequest Request;
typedef TeleportAbsoluteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportAbsolute
} // namespace turtlesim1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim1::TeleportAbsolute > {
  static const char* value()
  {
    return "a130bc60ee6513855dc62ea83fcc5b20";
  }

  static const char* value(const ::turtlesim1::TeleportAbsolute&) { return value(); }
};

template<>
struct DataType< ::turtlesim1::TeleportAbsolute > {
  static const char* value()
  {
    return "turtlesim1/TeleportAbsolute";
  }

  static const char* value(const ::turtlesim1::TeleportAbsolute&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim1::TeleportAbsoluteRequest> should match 
// service_traits::MD5Sum< ::turtlesim1::TeleportAbsolute > 
template<>
struct MD5Sum< ::turtlesim1::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::TeleportAbsolute >::value();
  }
  static const char* value(const ::turtlesim1::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::TeleportAbsoluteRequest> should match 
// service_traits::DataType< ::turtlesim1::TeleportAbsolute > 
template<>
struct DataType< ::turtlesim1::TeleportAbsoluteRequest>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::TeleportAbsolute >::value();
  }
  static const char* value(const ::turtlesim1::TeleportAbsoluteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim1::TeleportAbsoluteResponse> should match 
// service_traits::MD5Sum< ::turtlesim1::TeleportAbsolute > 
template<>
struct MD5Sum< ::turtlesim1::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::TeleportAbsolute >::value();
  }
  static const char* value(const ::turtlesim1::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::TeleportAbsoluteResponse> should match 
// service_traits::DataType< ::turtlesim1::TeleportAbsolute > 
template<>
struct DataType< ::turtlesim1::TeleportAbsoluteResponse>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::TeleportAbsolute >::value();
  }
  static const char* value(const ::turtlesim1::TeleportAbsoluteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM1_MESSAGE_TELEPORTABSOLUTE_H
