// Generated by gencpp from file turtlesim1/SetPen1.msg
// DO NOT EDIT!


#ifndef TURTLESIM1_MESSAGE_SETPEN1_H
#define TURTLESIM1_MESSAGE_SETPEN1_H

#include <ros/service_traits.h>


#include <turtlesim1/SetPen1Request.h>
#include <turtlesim1/SetPen1Response.h>


namespace turtlesim1
{

struct SetPen1
{

typedef SetPen1Request Request;
typedef SetPen1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPen1
} // namespace turtlesim1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim1::SetPen1 > {
  static const char* value()
  {
    return "9f452acce566bf0c0954594f69a8e41b";
  }

  static const char* value(const ::turtlesim1::SetPen1&) { return value(); }
};

template<>
struct DataType< ::turtlesim1::SetPen1 > {
  static const char* value()
  {
    return "turtlesim1/SetPen1";
  }

  static const char* value(const ::turtlesim1::SetPen1&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim1::SetPen1Request> should match 
// service_traits::MD5Sum< ::turtlesim1::SetPen1 > 
template<>
struct MD5Sum< ::turtlesim1::SetPen1Request>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::SetPen1 >::value();
  }
  static const char* value(const ::turtlesim1::SetPen1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::SetPen1Request> should match 
// service_traits::DataType< ::turtlesim1::SetPen1 > 
template<>
struct DataType< ::turtlesim1::SetPen1Request>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::SetPen1 >::value();
  }
  static const char* value(const ::turtlesim1::SetPen1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim1::SetPen1Response> should match 
// service_traits::MD5Sum< ::turtlesim1::SetPen1 > 
template<>
struct MD5Sum< ::turtlesim1::SetPen1Response>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::SetPen1 >::value();
  }
  static const char* value(const ::turtlesim1::SetPen1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::SetPen1Response> should match 
// service_traits::DataType< ::turtlesim1::SetPen1 > 
template<>
struct DataType< ::turtlesim1::SetPen1Response>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::SetPen1 >::value();
  }
  static const char* value(const ::turtlesim1::SetPen1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM1_MESSAGE_SETPEN1_H
