// Generated by gencpp from file turtlesim1/TeleportRelative1.msg
// DO NOT EDIT!


#ifndef TURTLESIM1_MESSAGE_TELEPORTRELATIVE1_H
#define TURTLESIM1_MESSAGE_TELEPORTRELATIVE1_H

#include <ros/service_traits.h>


#include <turtlesim1/TeleportRelative1Request.h>
#include <turtlesim1/TeleportRelative1Response.h>


namespace turtlesim1
{

struct TeleportRelative1
{

typedef TeleportRelative1Request Request;
typedef TeleportRelative1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TeleportRelative1
} // namespace turtlesim1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlesim1::TeleportRelative1 > {
  static const char* value()
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const ::turtlesim1::TeleportRelative1&) { return value(); }
};

template<>
struct DataType< ::turtlesim1::TeleportRelative1 > {
  static const char* value()
  {
    return "turtlesim1/TeleportRelative1";
  }

  static const char* value(const ::turtlesim1::TeleportRelative1&) { return value(); }
};


// service_traits::MD5Sum< ::turtlesim1::TeleportRelative1Request> should match 
// service_traits::MD5Sum< ::turtlesim1::TeleportRelative1 > 
template<>
struct MD5Sum< ::turtlesim1::TeleportRelative1Request>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::TeleportRelative1 >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelative1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::TeleportRelative1Request> should match 
// service_traits::DataType< ::turtlesim1::TeleportRelative1 > 
template<>
struct DataType< ::turtlesim1::TeleportRelative1Request>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::TeleportRelative1 >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelative1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlesim1::TeleportRelative1Response> should match 
// service_traits::MD5Sum< ::turtlesim1::TeleportRelative1 > 
template<>
struct MD5Sum< ::turtlesim1::TeleportRelative1Response>
{
  static const char* value()
  {
    return MD5Sum< ::turtlesim1::TeleportRelative1 >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelative1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlesim1::TeleportRelative1Response> should match 
// service_traits::DataType< ::turtlesim1::TeleportRelative1 > 
template<>
struct DataType< ::turtlesim1::TeleportRelative1Response>
{
  static const char* value()
  {
    return DataType< ::turtlesim1::TeleportRelative1 >::value();
  }
  static const char* value(const ::turtlesim1::TeleportRelative1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLESIM1_MESSAGE_TELEPORTRELATIVE1_H
