// Generated by gencpp from file ping/PingPong.msg
// DO NOT EDIT!


#ifndef PING_MESSAGE_PINGPONG_H
#define PING_MESSAGE_PINGPONG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ping
{
template <class ContainerAllocator>
struct PingPong_
{
  typedef PingPong_<ContainerAllocator> Type;

  PingPong_()
    : mssg()  {
    }
  PingPong_(const ContainerAllocator& _alloc)
    : mssg(_alloc)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mssg_type;
  _mssg_type mssg;




  typedef boost::shared_ptr< ::ping::PingPong_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ping::PingPong_<ContainerAllocator> const> ConstPtr;

}; // struct PingPong_

typedef ::ping::PingPong_<std::allocator<void> > PingPong;

typedef boost::shared_ptr< ::ping::PingPong > PingPongPtr;
typedef boost::shared_ptr< ::ping::PingPong const> PingPongConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ping::PingPong_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ping::PingPong_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ping

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'ping': ['/home/ashishk/workspace/src/ping/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ping::PingPong_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ping::PingPong_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping::PingPong_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ping::PingPong_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping::PingPong_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ping::PingPong_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ping::PingPong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "65cfd733252c7e3b8837b23ff1cb9e2f";
  }

  static const char* value(const ::ping::PingPong_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x65cfd733252c7e3bULL;
  static const uint64_t static_value2 = 0x8837b23ff1cb9e2fULL;
};

template<class ContainerAllocator>
struct DataType< ::ping::PingPong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ping/PingPong";
  }

  static const char* value(const ::ping::PingPong_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ping::PingPong_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mssg\n\
";
  }

  static const char* value(const ::ping::PingPong_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ping::PingPong_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mssg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct PingPong_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ping::PingPong_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ping::PingPong_<ContainerAllocator>& v)
  {
    s << indent << "mssg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mssg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PING_MESSAGE_PINGPONG_H
